const ALERT = 'ALERT'
const REFETCH_CHATS = 'REFETCH_CHATS'

const NEW_ATTACHMENTS = 'NEW_ATTACHMENTS'
const NEW_MESSSAGE_ALERT = "NEW_MESSAGE_ALERT"

const NEW_REQUEST = "NEW_REQUEST"

const NEW_MESSAGE = "NEW_MESSAGE"

const TYPING_START = "TYPING_START"
const TYPING_END = "TYPING_END"

const CHAT_JOINED = "CHAT_JOINED"
const CHAT_LEAVED = "CHAT_LEAVED"

const ONLINE_USERS = "ONLINE_USERS"

export {
    ALERT,
    REFETCH_CHATS,
    NEW_ATTACHMENTS,
    NEW_MESSSAGE_ALERT,
    NEW_REQUEST,
    NEW_MESSAGE,
    TYPING_START,
    TYPING_END,
    CHAT_JOINED,
    CHAT_LEAVED,
    ONLINE_USERS
}